#!/bin/sh
# Exit on error.
set -e

if ! bun run format:check; then
  printf "\n❌ Formatting check failed. Run 'bun run format' and try again.\n\n"
  exit 1
fi

if ! bun run lint; then
  printf "\n❌ Lint check failed. Run 'bun run lint:fix' or fix the errors above and try again.\n\n"
  exit 1
fi
